r"""
scripts/generate_tables.py — Emit every LaTeX table and number in the report.

This is the other half of the "one source of truth" discipline. `generate_figures.py`
makes the plots; this makes the tables AND the numbers that appear in the prose.

The prose problem it solves: a table can be regenerated, but a sentence that says
"P5 reached 54\%" is just characters — nothing recomputes it, so it silently rots
the moment the scorer changes (which is exactly what happened: the report said 54%
while the logs said 54.5%). The fix is `numbers.tex`, a file of LaTeX macros:

    \newcommand{\accPfiveMcq}{54.5\%}

The chapter writes `\accPfiveMcq{}` and never a literal. A scorer change then
propagates into the *sentences*, not just the tables.

Everything is read through `evaluation.loading.load_run`, so tables, figures and
prose are computed from the same bytes by the same code path. Drift becomes
structurally impossible rather than merely currently-absent, and
`tests/regression/test_no_number_drift.py` fails the build if anyone hand-edits an
emitted file.

ROUNDING — one rule, applied everywhere (a number must not print as 50% in a table
and 49.5% in a macro):
    percentages  1 d.p.    token-F1  3 d.p.    latency  0 d.p. seconds

Usage:
    python scripts/generate_tables.py
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from medrag_adaptive.evaluation.loading import load_run, load_run_with_report
from medrag_adaptive.evaluation.metrics import (
    aggregate_summary,
    proportion_diff_interval,
    risk_stratified_summary,
    DEFAULT_THRESHOLDS,
)

RAW = Path("results/raw_logs")
OUT = Path("results/tables")

# The four policies on the real corpus. P3 is daggered everywhere: it is
# closed-book, so its log is corpus-independent (verified: identical question-ids
# in identical order, zero retrievals). See test_p3_corpus_independence.py.
MCQ = {
    "P1 always-retrieve": "p1_medcorp_mcq.jsonl",
    "P4 hybrid":          "p4_medcorp_mcq.jsonl",
    "P3 closed-book$^\\dagger$": "p3_mirage200.jsonl",
    "P5 gated (calib.)":  "p5_medcorp_mcq.jsonl",
}
OPEN = {
    "P1 always-retrieve": "p1_medcorp_open.jsonl",
    "P3 closed-book$^\\dagger$": "pubmedqa_p3_open.jsonl",
    "P5 gated (calib.)":  "p5_medcorp_open.jsonl",
}


# ── formatting: the single rounding rule ──────────────────────────────

def pct(x: float) -> str:
    return "---" if x != x else f"{100 * x:.1f}\\%"


def f1(x: float) -> str:
    return f"{x:.3f}"


def secs(x: float) -> str:
    return f"{x:.0f}\\,s"


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def _header(script_rel: str) -> str:
    return (
        f"% AUTO-GENERATED by {script_rel} -- DO NOT EDIT.\n"
        f"% Regenerate with: python {script_rel}\n"
        f"% Every number is computed from results/raw_logs/ via evaluation.loading.\n"
        f"% git {_git_sha()} | {datetime.now():%Y-%m-%d %H:%M}\n"
    )


def write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(_header("scripts/generate_tables.py") + body,
                            encoding="utf-8")
    print(f"[ok] {OUT / name}")


# ── tables ─────────────────────────────────────────────────────────────

def tab_main_results() -> None:
    """The core results table: all policies, both question types."""
    rows = []
    for label, fn in MCQ.items():
        s = aggregate_summary(load_run(RAW / fn))
        rows.append(f"    {label} & MCQ & {pct(s.accuracy)} & {pct(s.retrieval_rate)} "
                    f"& {secs(s.mean_latency_s)} \\\\")
    rows.append("    \\midrule")
    for label, fn in OPEN.items():
        s = aggregate_summary(load_run(RAW / fn))
        rows.append(f"    {label} & open & {f1(s.mean_f1)} & {pct(s.retrieval_rate)} "
                    f"& {secs(s.mean_latency_s)} \\\\")

    body = f"""\\begin{{table}}[t]
  \\centering
  \\begin{{tabular}}{{llccc}}
    \\toprule
    Policy & Type & Accuracy / F1 & Retrieval & Latency/q \\\\
    \\midrule
{chr(10).join(rows)}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{All policies on the real MedCorp corpus (425{{,}}847 chunks), quantised
  Llama-3.2-3B. Multiple-choice is scored by accuracy; open-ended by mean token-F1
  (binary accuracy is not defined for open-ended answers -- see
  Section~\\ref{{sec:eval-ablation}}). $^{{\\dagger}}$P3 never retrieves, so its result is
  corpus-independent; it is a paired run over the identical question set.}}
  \\label{{tab:main-results}}
\\end{{table}}
"""
    write("tab_main_results.tex", body)


def tab_risk() -> None:
    """Risk-stratified accuracy with Wilson intervals — the small-n caveat."""
    rows = []
    for label, fn in MCQ.items():
        out = risk_stratified_summary(load_run(RAW / fn))
        cells = []
        for risk in ("low", "medium", "high"):
            c = out[risk]
            cells.append(f"{pct(c['accuracy'])} [{100*c['ci_low']:.0f}, {100*c['ci_high']:.0f}]")
        rows.append(f"    {label} & " + " & ".join(cells) + " \\\\")

    ns = risk_stratified_summary(load_run(RAW / MCQ["P5 gated (calib.)"]))
    body = f"""\\begin{{table}}[t]
  \\centering
  \\begin{{tabular}}{{lccc}}
    \\toprule
    & \\multicolumn{{3}}{{c}}{{Accuracy \\% [95\\% Wilson CI]}} \\\\
    \\cmidrule(lr){{2-4}}
    Policy & Low ($n={ns['low']['n']}$) & Medium ($n={ns['medium']['n']}$) & High ($n={ns['high']['n']}$) \\\\
    \\midrule
{chr(10).join(rows)}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{Multiple-choice accuracy by clinical risk level, with 95\\% Wilson score
  intervals. The high-risk stratum contains only $n={ns['high']['n']}$ questions, giving intervals
  roughly $\\pm$30 percentage points wide: \\emph{{no comparison between policies at high
  risk is statistically meaningful in this evaluation}}. The medium stratum
  ($n={ns['medium']['n']}$) is where the headline comparison actually rests, and even there the
  intervals overlap.}}
  \\label{{tab:risk}}
\\end{{table}}
"""
    write("tab_risk.tex", body)


def tab_setup() -> None:
    """Policy definitions — the ruler, stated before anything is measured."""
    body = """\\begin{table}[t]
  \\centering
  \\begin{tabular}{llll}
    \\toprule
    Policy & Retrieval & Gate & Role in the evaluation \\\\
    \\midrule
    P1 always-retrieve & every query & --- & retrieval baseline \\\\
    P4 hybrid & every query & --- & BM25\\,+\\,dense fusion (RRF) \\\\
    P3 closed-book$^{\\dagger}$ & never & --- & parametric-knowledge reference \\\\
    P5 gated & selective & 3-gate ensemble & the proposed method \\\\
    \\bottomrule
  \\end{tabular}
  \\caption{The four policies compared. P5 decides per query whether to retrieve,
  using a majority vote ($\\geq$2 of 3) over the token-entropy, logit-margin and
  hallucination-probe gates. $^{\\dagger}$P3 never retrieves and is therefore
  corpus-independent.}
  \\label{tab:setup}
\\end{table}
"""
    write("tab_setup.tex", body)


# ── numbers.tex: the macros the prose uses ─────────────────────────────

def numbers() -> None:
    """Emit every number the chapter cites, as a LaTeX macro.

    The chapter must never contain a literal figure. This is what makes a scorer
    change propagate into the sentences rather than silently rotting them.
    """
    lines = []

    def mac(name: str, value: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    # MCQ headline numbers
    summaries = {}
    for key, fn in [("Pone", "p1_medcorp_mcq.jsonl"), ("Pfour", "p4_medcorp_mcq.jsonl"),
                    ("Pthree", "p3_mirage200.jsonl"), ("Pfive", "p5_medcorp_mcq.jsonl")]:
        s = aggregate_summary(load_run(RAW / fn))
        summaries[key] = s
        mac(f"acc{key}Mcq", pct(s.accuracy))
        mac(f"ret{key}Mcq", pct(s.retrieval_rate))
        mac(f"lat{key}Mcq", secs(s.mean_latency_s))

    # Open-ended headline numbers
    for key, fn in [("Pone", "p1_medcorp_open.jsonl"), ("Pthree", "pubmedqa_p3_open.jsonl"),
                    ("Pfive", "p5_medcorp_open.jsonl")]:
        s = aggregate_summary(load_run(RAW / fn))
        mac(f"f1{key}Open", f1(s.mean_f1))
        mac(f"ret{key}Open", pct(s.retrieval_rate))

    # THE headline claim, computed with its uncertainty rather than asserted.
    p5, p1 = summaries["Pfive"], summaries["Pone"]
    diff, lo, hi = proportion_diff_interval(
        round(p5.accuracy * p5.n), p5.n, round(p1.accuracy * p1.n), p1.n
    )
    mac("diffPfivePone", f"{100 * diff:.1f}")
    mac("diffPfivePoneCI", f"[{100 * lo:.1f}, {100 * hi:.1f}]")

    # Provenance: how many records the corrected extractor changed.
    _, rep = load_run_with_report(RAW / "p5_medcorp_mcq.jsonl")
    mac("rescoredPfive", str(rep.rescored))
    mac("nQuestions", str(rep.n))

    # Safety bars.
    for risk, bar in DEFAULT_THRESHOLDS.items():
        mac(f"bar{risk.capitalize()}", f"{100 * bar:.0f}\\%")

    # Distance to the nearest safety bar (P3 is the best policy on MCQ).
    gap = DEFAULT_THRESHOLDS["low"] - summaries["Pthree"].accuracy
    mac("gapToLowBar", f"{100 * gap:.1f}")

    write("numbers.tex", "\n".join(lines) + "\n")


def main() -> None:
    tab_setup()
    tab_main_results()
    tab_risk()
    numbers()
    print(f"\nTables written to {OUT}/")


if __name__ == "__main__":
    main()
